version: "3"
services:
  piece16:
    container_name: piece16_app
    env_file:
      - .env
    build: .
    ports:
    - 8088:8088
    restart: on-failure
    volumes:
    - piece16_app:/usr/src/app/
    depends_on:
      - postgres_db
    networks:
      - fullstack


  postgres_db:
    image: postgres:latest
    container_name: piece16_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
    - 5431:5432
    volumes:
    - piece16_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  piece16_app:
  piece16_postgres:

networks:
  fullstack:
    driver: bridge