version: 1.0
server:
    idleTimeout: 120s
    readTimeout: 1s
    writeTimeout: 1s
db:
    postgres:
        host: ""
        port: ""
        username: ""
        password: ""
        dbname: ""
        sslmode: ""
        driver: "pgx"
log:
    level: "Debug"
    codes:
#   global:
        1000en: "unknown error"
#   initialization:
        2000en: "error loading .env / system environment"
        2001en: "Can't set log level mode, default: [info]"
        2002en: "Can't load environments or .env file"
#   dataBase:
        3000en: "Cannot get connection to db"
        3001en: "Common db errors"
#   server:
        4001en: "Server starting..."
        4002en: "Received terminate, server shutting down..."
